"""empty message

Revision ID: 63f557080e8a
Revises: 
Create Date: 2026-09-22 20:28:18.021334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f557080e8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('direct', 'group', name='chat_type'), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('avatar_key', sa.String(length=1024), nullable=True),
    sa.Column('direct_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['last_message_id'], ['message.id'], name='fk_chat_last_message', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat')),
    sa.UniqueConstraint('direct_key', name=op.f('uq_chat_direct_key'))
    )
    op.create_index(op.f('ix_chat_last_message_at'), 'chat', ['last_message_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('avatar_key', sa.String(length=1024), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('fk_message_chat_id_chat'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_message_sender_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_index('ix_message_chat_id_id', 'message', ['chat_id', 'id'], unique=False)
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('fk_attachment_chat_id_chat'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_attachment_message_id_message'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], name=op.f('fk_attachment_uploader_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment')),
    sa.UniqueConstraint('key', name=op.f('uq_attachment_key'))
    )
    op.create_index(op.f('ix_attachment_chat_id'), 'attachment', ['chat_id'], unique=False)
    op.create_index(op.f('ix_attachment_message_id'), 'attachment', ['message_id'], unique=False)
    op.create_table('chat_member',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('fk_chat_member_chat_id_chat'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['message.id'], name=op.f('fk_chat_member_last_read_message_id_message'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_member_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('pk_chat_member'))
    )
    op.create_index('ix_chat_member_user_chat', 'chat_member', ['user_id', 'chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_member_user_chat', table_name='chat_member')
    op.drop_table('chat_member')
    op.drop_index(op.f('ix_attachment_message_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_chat_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_index('ix_message_chat_id_id', table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_chat_last_message_at'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
